name: 🚀 Deploy wildernis-onder-water.be !

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - run: npm install
      - run: npm build

      - name: List output files
        run: ls

      - name: 📂 Upload dist to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: domains/wildernisonderwater.be/public_html/
          #server-dir: domains/wildernisonderwater.be/public_html/
